if (APPLE)
    message("配置macOS OcrLib 路径: ${CMAKE_CURRENT_LIST_DIR}/Darwin-CLIB-CPU")
    set(OcrLib_DIR "${CMAKE_CURRENT_LIST_DIR}/Darwin-CLIB-CPU")
elseif (WIN32)
    if (CMAKE_CL_64)
        message("配置WINDOWS OcrLib x64 路径: ${CMAKE_CURRENT_LIST_DIR}/win-CLIB-CPU-x64")
        set(OcrLib_DIR "${CMAKE_CURRENT_LIST_DIR}/win-CLIB-CPU-x64")
    else ()
        message("配置WINDOWS OcrLib x86 路径: ${CMAKE_CURRENT_LIST_DIR}/win-CLIB-CPU-Win32")
        set(OcrLib_DIR "${CMAKE_CURRENT_LIST_DIR}/win-CLIB-CPU-Win32")
    endif ()
elseif (UNIX)
    message("配置Linux OcrLib 路径: ${CMAKE_CURRENT_LIST_DIR}/Linux-CLIB-CPU")
    set(OcrLib_DIR "${CMAKE_CURRENT_LIST_DIR}/Linux-CLIB-CPU")
endif ()

